<a href="https://colab.research.google.com/github/Junseokee/Study-Python/blob/main/220802_%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1_%ED%9A%8C%EA%B7%80%EC%9D%98_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 로지스틱 회귀
  
  - 분류 문제를 수행하는 모델.
  - 일반적인 회귀 문제와는 다르게 몇가지의 이산적인 값 중 하나를 선택하는 모델
  - 로지스틱 회귀는 분류 모델이다 예측 x

  - (복습) 오차가 작은지 확인하는건 비용함수이다. MSE, MAE 등
  - 회귀는 어떠한 연속적인 값


### 로짓함수 분류에 사용됨
#### 로지스틱
  - 시그모이드 함수 <- x값이 작아지면 작아질수록 0에 가깝게 수렴하고 커지면 1에 가깜게 수렴한다. 1과 0이 되지는 않는다. 1/(1+e^-z)
  - z는 가중치의 값과 피쳐값의 선형 결합
  - 이를 학습하기위해 경사하강법 적용

#### 비용함수
- 로지스틱 회귀도 선형회귀와 마찬가지로 예측값과 실제값 간의 차이를 최소하는 방향으로 학습
- 실제값이 1일때와 0일때 다른 식 적용
- h값이 1에 가까워질수록 비용함수는 0에가까워진다.
- h값이 0에 가까워질수록 0에 가까워진다.



### 분류 문제의 성능지표

 - 분류문제의 평가방법은 회귀, 분류, 클러스터링 등 문제 해결방법에 따라 다른 성능지표 사용
  - 회귀 : MAE, MSE, RMSE, R2, SSE
  - 분류 : 정확도, 정밀도, 민감도, F1 스코어, 컨퓨전매트릭스, ROC 커브(정밀도와 민감도로 그래프를 그림 *잘안쓰임, 기울기가 1에 가까울수록 좋다), 리프트 차트
  - 클러스터링 : DBI, 엘보우 메서드, 실루엣계수 <- 비지도학습이라 신뢰도가 떨어짐
 

### 혼동 행렬
  - 혼동행렬(confusion matrix)는 예측값이 실제값 대비 얼마나 잘맞는지 행렬로 표현하는 기법이다.
  - 행이 실제값 0이면 오답 1이면 정답
  - 열이 예측값
  - 1,1 = True Positive
  - 1,0 = False Positive
  - 0,1 = False Negetive
  - 0,0 = True Negetive 

In [3]:
from sklearn.metrics import confusion_matrix
y_true = [1,0,1,1,0,1]
y_pred = [0,0,1,1,0,1]
confusion_matrix(y_true, y_pred)

array([[2, 0],
       [1, 3]])

In [7]:
tn, fp, fn, tp = confusion_matrix(y_true,y_pred).ravel() #ravel() : 2차원 배열을 1차원으로 펴줌
(tn,fp,fn,tp)

(2, 0, 1, 3)

In [8]:
confusion_matrix(y_true, y_pred)

array([[2, 0],
       [1, 3]])

### 혼동행렬표를 사용한 지표
  - accuracy(정확도) : 단순히 얼마나 맞췄는지를 측정하는 정보
  - precision(정밀도) : 1이라고 예측했을때 그 값이 얼마나 정답이었는지 보여줌
  - recall(민감도,재현률) : 1인값을 얼마나 안놓치고 정답으로 맞추는지에 대한 지표




  - 정확도 = 전체 데이터 갯수 대비 정답 갯수의미
    - ACC = TP+TN/(전체 데이터)
    - 정확도만 믿으면 안됨
    

In [10]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = np.array([0,1,1,0])
y_true = np.array([0,1,0,0])
sum(y_true == y_pred) / len(y_true)

0.75

In [11]:
accuracy_score(y_true, y_pred)

0.75

In [12]:
# 오차율 = 오답을 맞춘갯수
# ERR = 1-ACC
err_rate = 1-accuracy_score(y_true,y_pred)
err_rate

0.25

- 정밀도 민감도(재현률), F1 스코어
  - 정밀도, 민감도(재현률)는 불균형한 데이터셋을 다룰 때 유용한 지표이다
  - 정밀도와 민감도는 trade off 관계라서 반비례 관계이다.
  - 서로 교차되는 지점이 제일 좋다.
  
- 정밀도 : 모델이 1이라고 예측했을때 그 값이 얼마나 정답이었는지를 보여주는 지표, 아래 수식에서 분모는 모델이 1이라고 예측한 데이터의 수이며 분자는 맞은 정답의 갯수
  - PPV(Precision) = TP/TP+FP

- 민감도 : 1인값을 얼마나 안놓치고 맞췄는지에 대한 지표. 분모는 실제값이 1인 데이터의 갯수 분자는 모델이 제대로 맞춘 데이터의 갯수
  - RECALL(TPR) = TP/TP+FN

- F1 스코어 : 정밀도와 민감도를 통합한 지표로 정밀도와 민감도의 조화평균값. 모델의 성능이 좋은지를 확인할때 한개의 지표로 정리할 필요가 있을때 적합한 지표중 하나.
  - Precision-RECALL / Precision+RECALL

In [13]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

y_pred = np.array([0,1,1,0,1,1,1,0])
y_true = np.array([0,1,0,0,0,0,1,1])

In [14]:
precision_score(y_true, y_pred) # 정밀도

0.4

In [15]:
recall_score(y_true, y_pred) # 민감도

0.6666666666666666

In [16]:
f1_score(y_true, y_pred) # F1 스코어

0.5

### 로지스틱 회귀 구현하기
#### 로지스틱 회귀 구현을 위한 함수
  - 로지스틱 회귀의 구현은 선형회귀의 구현과 사실상 동일한 방식이다.
  - 시그모이드 함수 만들기
    - def sigmoid(z):
      - return 1 / (1+np.exp(z))

    

### 가설함수
  - 시그모이드 함수를 약간 업데이트한 가설함수
    - 시그모이드 함수는 입력 값은 단순히 $z$를 사용하는데, 실제로는 피쳐값인 벡터

### 비용함수는 실제값이 0과 1일떄 다른 식으로 사용

### 경사하강법 : 가중치 업데이트


In [24]:
# 사이킷런을 통해 학습하기
# 와튼대학교의 'uva.csv' 데이터 사용
# 인터넷 사용자가 뉴비인지 아닌지 구별하는 데이터 셋

import pandas as pd
data_url = "http://www-stat.wharton.upenn.edu/~waterman/DataSets/uva.txt"

In [25]:
#!pip install fsspec

In [28]:
df = pd.read_table(data_url) # Tab문자로 구별된 파일이라 Table로 연다
df.head()

who  Newbie   Age  Gender Household Income Sexual Preference  \
0  id74364       0  54.0    Male           $50-74          Gay male   
1  id84505       0  39.0  Female        Over $100      Heterosexual   
2  id84509       1  49.0  Female           $40-49      Heterosexual   
3  id87028       1  22.0  Female           $40-49      Heterosexual   
4  id76087       0  20.0    Male           $30-39          Bisexual   

      Country Education Attainment Major Occupation Marital Status  \
0     Ontario         Some College         Computer          Other   
1      Sweden         Professional            Other          Other   
2  Washington         Some College       Management          Other   
3     Florida         Some College         Computer        Married   
4  New Jersey         Some College        Education         Single   

  Years on Internet  
0            4-6 yr  
1            1-3 yr  
2        Under 6 mo  
3           6-12 mo  
4            1-3 yr

### 데이터 전처리

In [29]:
# pop 메서드는 DataFrame에서 열 레이블을 꺼낸다. 즉 원본 DataFame에서 해당 열이 제거
df.pop('who') # 개인 ID
df.pop('Country') #거주지
df.pop('Years on Internet') # newbie와 겹치기때문에 삭제

df.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
dtype: object

In [32]:
# catergory 변수를 원핫인코딩 형태로 바꾸기 위해 타입 변경

category_cols = ['Gender','Household Income','Sexual Preference',
            'Education Attainment', 'Major Occupation', 'Marital Status']

In [35]:
for col in category_cols: # 판다스에서제공하는 category 자료형으로 변경
  df[col] = df[col].astype('category') # 반복문을 통해 타입 변경

df.dtypes

Newbie                     int64
Age                      float64
Gender                  category
Household Income        category
Sexual Preference       category
Education Attainment    category
Major Occupation        category
Marital Status          category
dtype: object

In [38]:
df_onehot = pd.get_dummies(df)

In [53]:
df_onehot.shape

(19583, 38)

In [54]:
df_onehot.isnull().sum()

Newbie                               0
Age                                  0
Gender_Female                        0
Gender_Male                          0
Household Income_$10-19              0
Household Income_$20-29              0
Household Income_$30-39              0
Household Income_$40-49              0
Household Income_$50-74              0
Household Income_$75-99              0
Household Income_Over $100           0
Household Income_Under $10           0
Sexual Preference_Bisexual           0
Sexual Preference_Gay male           0
Sexual Preference_Heterosexual       0
Sexual Preference_Lesbian            0
Sexual Preference_Transgender        0
Sexual Preference_na                 0
Education Attainment_College         0
Education Attainment_Doctoral        0
Education Attainment_Grammar         0
Education Attainment_High School     0
Education Attainment_Masters         0
Education Attainment_Other           0
Education Attainment_Professional    0
Education Attainment_Some

In [55]:
# age의 널값을 평균값으로 대체, fillna로 하는게 더 간편
df_onehot.loc[pd.isnull(df_onehot['Age']),'Age'] = df_onehot['Age'].mean()

In [56]:
df_onehot.isnull().sum()

Newbie                               0
Age                                  0
Gender_Female                        0
Gender_Male                          0
Household Income_$10-19              0
Household Income_$20-29              0
Household Income_$30-39              0
Household Income_$40-49              0
Household Income_$50-74              0
Household Income_$75-99              0
Household Income_Over $100           0
Household Income_Under $10           0
Sexual Preference_Bisexual           0
Sexual Preference_Gay male           0
Sexual Preference_Heterosexual       0
Sexual Preference_Lesbian            0
Sexual Preference_Transgender        0
Sexual Preference_na                 0
Education Attainment_College         0
Education Attainment_Doctoral        0
Education Attainment_Grammar         0
Education Attainment_High School     0
Education Attainment_Masters         0
Education Attainment_Other           0
Education Attainment_Professional    0
Education Attainment_Some

### 데이터 분리

In [57]:
x_data = df_onehot.iloc[:, 1:].values # 전체행에서 1번만 부터 값을 넣음
y_data = df_onehot.iloc[:, 0].values.reshape(-1,1) # 0번째 행만 값을 넣음 (정답 y값 = Newbie 여부)
y_data.shape, x_data.shape

((19583, 1), (19583, 37))

In [58]:
from sklearn import preprocessing # Min-Max Standardzation

min_max_scaler = preprocessing.MinMaxScaler()
x_data = min_max_scaler.fit_transform(x_data) # 스케일링과 fit, transform 동시에

In [59]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split( #train set 과 test set 분리
    x_data, y_data, test_size=0.33, random_state=42)
X_train.shape, X_test.shape

((13120, 37), (6463, 37))

In [60]:
from sklearn.linear_model import LogisticRegression # 선형에 있지만 분류모델임

logreg = LogisticRegression(fit_intercept = True) # 로지스틱 회귀모델 학습 , fit_intercept = 절편사용유무
logreg.fit(X_train, y_train.flatten()) # flatten() 2차원 배열을 평평하게 펴주는 함수

LogisticRegression()

In [51]:
# # LosisticRegression 클래스 입력파라미터 종류
# LogisticRegression(penalty='l2', max_iter = 100, # 규제에 사용될 기준지정(l1,l2,elasticnet,None) - default : l2, 기울기 값찾는 반복 수
#                     n_jobs=None) # 사용코어 갯수 defult = 1개, -1은 모든 코어
                   

LogisticRegression()

penalty : 규제에 사용 된 기준을 지정 (l1, l2, elasticnet, none) – default : l2
dual : 이중 또는 초기 공식
tol : 정밀도
C : 규제 강도
fit_intercept : 모형에 상수항 (절편)이 있는가 없는가를 결정하는 인수 (default : True)
intercept_scaling : 정규화 효과 정도
class_weight : 클래스의 가중치
random_state : 난수 seed 설정
solver : 최적화 문제에 사용하는 알고리즘
max_iter : 계산에 사용할 작업 수
multi_class : 다중 분류 시에 (ovr, multinomial, auto)로 설정
verbose : 동작 과정에 대한 출력 메시지
warm_start : 이전 모델을 초기화로 적합하게 사용할 것인지 여부
n_jobs : 병렬 처리 할 때 사용되는 CPU 코어 수
l1_ratio : L1 규제의 비율(Elastic-Net 믹싱 파라미터 경우에만 사용)

#### 값 예측하기와 성능 측정하기

In [61]:
logreg.predict_proba(X_test[:5]) # 0열 : 0 , 1열 : 1, 큰값으로 예측한다, 5개 모두 0으로 예측함

array([[0.56843257, 0.43156743],
       [0.91112573, 0.08887427],
       [0.79481084, 0.20518916],
       [0.85841562, 0.14158438],
       [0.62764602, 0.37235398]])

In [63]:
logreg.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

y_true = y_test.copy()
y_pred = logreg.predict(X_test)
confusion_matrix(y_true, y_pred)

array([[4487,  275],
       [1350,  351]])

In [66]:
accuracy_score(y_true, y_pred) # 엄청틀렸는데 0의 값이 압도적으로 많아서 ACC가 높게나옴

0.7485687761101656