https://drive.google.com/file/d/11y3dj4r-FMYHSJs298MPdqdOsNSRzKyM/view #무슨 데이터
https://han.gl/LwZOD #하우스 데이터 링크 
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data #하우스 데이터


In [1]:
import pandas as pd
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"
df_data = pd.read_csv(data_url, sep = '\s+', header = None) # csv로 로드 sep = '\s+'(공백으로 칸을 나누는데 여러개일수도 있음)
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS',
                  'NOX', 'RM', 'AGE','DIS','RAD',
                  'TAX','PTRATIO','B','LSTAT','MEDV']
df_data.head()


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [2]:
import numpy as np

df_data['weight_0'] = 1 # weight 0 칼럼 추가
df_data = df_data.drop("MEDV", axis=1) # Y값을 제거
df_matrix = df_data.values # 행렬 데이터로 변환 .values 함수 -> 컬럼과 테이블 말고 데이터만 가져옴
weight_vector = np.random.random_sample((14,1)) # 가중치 w 생성 (랜덤하게 만든 임의값)
df_matrix.dot(weight_vector) # 내적 연산 실행 결과 출력

array([[ 614.88713341],
       [ 566.78199356],
       [ 549.9009266 ],
       [ 520.62024234],
       [ 528.85998819],
       [ 530.18675818],
       [ 634.56388783],
       [ 658.84591652],
       [ 657.36782094],
       [ 644.48446718],
       [ 655.18451312],
       [ 647.99916788],
       [ 611.66168155],
       [ 618.1243626 ],
       [ 623.64855656],
       [ 613.28943734],
       [ 587.13918885],
       [ 627.04187726],
       [ 527.22780922],
       [ 619.82154902],
       [ 633.36674114],
       [ 636.05186036],
       [ 642.00557347],
       [ 646.77521756],
       [ 641.67141261],
       [ 574.39742251],
       [ 626.97179751],
       [ 578.88276995],
       [ 636.84971208],
       [ 626.17573535],
       [ 620.06748588],
       [ 633.29713394],
       [ 526.417111  ],
       [ 618.48038434],
       [ 546.02699516],
       [ 595.61796377],
       [ 578.04539176],
       [ 576.29544195],
       [ 565.98781741],
       [ 581.20477705],
       [ 576.30028123],
       [ 495.522

In [3]:
import numpy as np
test_array = np.array([1,4,5,8])
test_array

array([1, 4, 5, 8])

In [4]:
type(test_array[3])

numpy.int32

In [5]:
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [8]:
type(test_array[3])

numpy.float64

In [14]:
test_array = np.array([1,4,5,"8"], float)
print(test_array) # 넘파이 배열은 쉼표가 없음

[1. 4. 5. 8.]


In [15]:
print(type(test_array[3])) # 형변환
print(test_array.dtype) #배열 전체 타입
(test_array.shape) # 배열의 구조를 반환함 1차원 요소값만 4개

<class 'numpy.float64'>
float64


(4,)

In [16]:
matrix = [[1,2,5,8],
          [1,2,5,8],
          [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [18]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [20]:
np.array(tensor_rank3, int).ndim #차원 알아보기

3

In [21]:
np.array(tensor_rank3, int).size # 크기 알아보기

48

In [25]:
#dtype 함수로 원하는 데이터 형태로 저장 가능하다.
np.array([[1,2,3.7], [4,5,6.5]], dtype=int ) #정수형 선언으로 소숫점 밑은 절삭

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.array([[1,2,3.7], [4,5,6.5]], dtype=float )

array([[1. , 2. , 3.7],
       [4. , 5. , 6.5]])

In [26]:
np.array([[1,2,3.5], [4,5,6.5]]) # 생략시 가장 포함할수 있는 타입으로 선언

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [27]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=np.float64).itemsize # 차지하는 바이트를 출력 (메모리할당량)

8

In [28]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=np.float32).itemsize

4

### 배열 구조 다루기
- 상황에따라 구조 변경할 경우엔 reshape 함수를 사용

In [29]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [30]:
x.reshape(-1,) # 축소?

array([1, 2, 5, 8, 1, 2, 5, 8])

In [32]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
x.reshape(2,4) # 분할 ? 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [40]:
x.reshape(2,-1) #-1은 전체요소의 갯수는 고정하고 전체요소 갯수를 고려하여 마지막 차원이 자동으로 지정되는 기법이다.

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
x.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [45]:
x.flatten() #데이터를 1차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7])

In [51]:
# 넘파이도 인덱싱과 슬라이싱 가능

x = np.array([[1,2,3],[4.5,5,6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
x[0][0] #[행][열]

1

In [53]:
x[0,2] #[행,열]

3

In [55]:
x[0,1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

#### 슬라이싱

In [56]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
x[:,2:] #전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [58]:
x[1,1:3] #1행의 1~2열

array([7, 8])

In [61]:
x[1:3] # 1행 ~ 2행의 전체

array([[ 6,  7,  8,  9, 10]])

In [62]:
x = np.array(range(15), int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [65]:
x[::2,::3] #::2 = 1,3 행만 선택 ::3 3칸씩마다

array([[ 0,  3],
       [10, 13]])

#### 배열생성 함수
    - arnage(시작인덱스, 마지막인덱스, 증가값) *실수형도 입력 가능

In [67]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(-5,5,2)

array([-5, -3, -1,  1,  3])

In [70]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

- ones, zeros, empty
- 추가로 ones_like 처럼 뒤에 _like를 붙으면 어떤 배열을 1,0 으로 반환

    - ones() : 1로만 구성된 넘파이 배열 생성
    - zeros() : 0으로만 구성된 넘파이 배열 생성
    - empty() : 활용가능한 메모리 공간 확보, 메모리 공간에 남은값 반환
    - 전부다 shape 파라미터로 크기 지정가능

In [71]:
np.ones(shape =(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [72]:
np.zeros(shape=(2,2), dtype = np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [74]:
np.empty(shape=(2,4), dtype = np.float32) #거의 안쓰임

array([[7.7103857e-26, 4.8344797e-43, 7.7107998e-26, 4.8344797e-43],
       [7.7107209e-26, 4.8344797e-43, 7.7108392e-26, 4.8344797e-43]],
      dtype=float32)

In [76]:
np.zeros(shape=x.shape, dtype = np.float32) #zeros_like와 동일하게 사용가능

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [78]:
#identity() : 단위행렬 생성

np.identity(n=3, dtype = int) #대각선이 1로 가득찬 단위행렬 생성

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [79]:
np.identity(n=4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [81]:
#eye() 함수는 동일하게 1을 생성하는 함수지만 시작점과 크기를 지정할 수 있음

np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [83]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
#diag 행렬값을 추출할때 사용 -> 대각행렬만 뽑을때 사용
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
np.diag(matrix)

array([0, 4, 8])

In [ ]:
np.diag(matrix, k = 1) #k로 시작점 사용가능

In [90]:
# 통계분석 함수
# uniform() -> 균등분포, normal() -> 정규분포

np.random.uniform(0,5,10) # np.random.uniform(시작값, 끝값, 데이터개수)

array([4.21711177, 4.27068809, 3.83609234, 2.7171139 , 3.4861444 ,
       0.63185384, 3.08115791, 4.25662143, 2.94806018, 1.65087567])

In [91]:
np.random.normal(0,2,10) # np.random.normal시작값, 분산, 데이터개수)

array([ 3.22805398,  2.55738837, -1.50900092, -2.81676538,  1.69928611,
        0.59524015, -2.27381348,  2.60292036,  2.87472027, -1.06075766])

## 넘파이 배열 연산

### 연산함수
    - std, mean, sum과 같은 함수 등
    - 중요한 개념은 축(axis)이다. 축은 배열의 구조(shape)를 설명할때 사용한 개념, 랭크(rank)가 증가할때마다 새로운 차원 이것이 축이라함
    
    식이나 수학 정리가 궁금하면 공돌이의 수학블로그 ㄱ

In [92]:
test_array = np.arange(1,11)
test_array.sum()

55

In [93]:
# 2차원 행렬값을  행또는 열을 기준으로 적용할떄 axis를 사용하여 연산을 수행

test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
test_array.sum(axis=0) # 0 = 세로로

array([15, 18, 21, 24])

In [95]:
test_array.sum(axis=1) # 1 = 가로로

array([10, 26, 42])

In [97]:
test_array = np.arange(1,13).reshape(3,4)

third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [98]:
third_order_tensor.sum(axis=0) #1+1+1

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [99]:
third_order_tensor.sum(axis=1) #1+5+9

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [100]:
third_order_tensor.sum(axis=2) # 1+2+3+4

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [102]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
test_array.mean(axis=1) # axis = 1축을 기준으로 평균 연ㅅㄴ

array([ 2.5,  6.5, 10.5])

In [106]:
test_array.std() # 전체 값에 대한 표준편차

3.452052529534663

In [107]:
test_array.std(axis=0) # axis = 0 축을 기준으로 표준편차 연산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [108]:
np.sqrt(test_array) # 각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [109]:
# 넘파이 연결 함수 축을 기준으로 발생
# 벡터간의 연결을 통해 행렬 생성 , vstack(수직스택), hstack(수평스택)
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [111]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [112]:
v2

array([[4],
       [5],
       [6]])

In [113]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [116]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.concatenate((v1,v2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [117]:
# concatenate 두개의 배열을 결합하는 함수
# axis로 행(0)기준 열(1) 기준 연결할지 선택가능

In [130]:
v1 = np.array([[1,2,3,4]]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [131]:
v2

array([[5],
       [6]])

In [132]:
np.concatenate((v1,v2), axis =1)

array([[1, 2, 5],
       [3, 4, 6]])

In [133]:
#사칙연산은 같은 위치에 행렬값끼리 곱해준다

x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [135]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [136]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [137]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [138]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [143]:
# 벡터의 내적 연산 (행렬곱) 
# (m x n)*(n x k) = (m x k)인 행렬이 결과로 나온다

x_1 = np.arange(1,7).reshape(2,3)
x_2 = np.arange(1,7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [145]:
x_1.dot(x_2) 

array([[22, 28],
       [49, 64]])

In [152]:
#브로드캐스팅 연산 -> 행렬과 하나의 값 or 벡터와 연산 하는 개념

x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [154]:
x//3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]], dtype=int32)

In [155]:
x%3

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [156]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [157]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [158]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### 비교 연산과 데이터 추출

    - boolean type 계산
    - 브로드캐스팅 연산도 가능

In [159]:
x = np.array([4,3,2,6,8,5])
x > 3

array([ True, False, False,  True,  True,  True])

In [160]:
x = np.array([1,3,9])
y = np.array([2,1,7]) #배열끼리도 비교 가능
x > y

array([False,  True,  True])

In [161]:
# all과 any 배열 내부의 값이 참인지 거짓인지에 따라 값 반환
# all() = 모든값이 참이면 True, 하나라도 아니면 False
# any() = 모든값중 하나라도 참이면 True, 모두 거짓이면 False

x = np.array([4,6,7,3,2])
(x>3)

array([ True,  True,  True, False, False])

In [162]:
(x>3).all()

False

In [163]:
(x>3).any()

True

In [164]:
(x<10).any()

True

In [166]:
(x>10).any()

False

In [167]:
# 인덱스 반환함수

x = np.array([4,6,7,3,2])
(x>5)

array([False,  True,  True, False, False])

In [169]:
np.where(x>5) # 조건 만족하는 값의 위치를 알려줌

(array([1, 2], dtype=int64),)

In [170]:

x = np.array([4,6,7,3,2])
np.where(x>5, 10, 20)

array([20, 10, 10, 20, 20])

In [176]:
x = np.array([4,6,7,3,2]) # 작은순의 배열내 순서를 반환
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [177]:
#불린 인덱스

x = np.array([4,6,7,3,2])
(x>3)

array([ True,  True,  True, False, False])

In [178]:
cond = x > 3
x[cond] # True 값만 저장한 변수

array([4, 6, 7])

In [182]:
con = x>3
x[con]

array([4, 6, 7])

In [180]:
x.shape

(5,)

In [183]:
cond.shape

(5,)

In [184]:
# fancy index

x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2],int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [185]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [186]:
x = np.array([[1,4],[9,16]], int)
a = np.array([0,1,1,1,0,0], int)
b = np.array([0,0,0,1,1,1], int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])